[build]
 command = "cd netlify/functions && npm install && cd ../.. && npx expo export -p web --output-dir dist && node scripts/process-figma-assets.js && node scripts/add-pwa-assets.js && node scripts/inject-backend-url.js && node scripts/copy-public.js"
 publish = "dist"
 functions = "netlify/functions"

[build.environment]
 # EXPO_PUBLIC_* variables are read during export and injection
 # Set in Netlify → Site Settings → Environment
 # Example: EXPO_PUBLIC_BACKEND_URL=https://<your-site>.netlify.app/.netlify/functions
 NODE_VERSION = "20"
 JWT_SECRET = "your-jwt-secret-key-here"

# SPA redirect rules for client-side routing
[[redirects]]
 from = "/*"
 to = "/index.html"
 status = 200